name: My CI/CD Workflow

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Agrega más pasos aquí según tus necesidades
      # Por ejemplo, puedes configurar pruebas, despliegues, etc.
